version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://localhost
      NEXT_PUBLIC_USER_SERVICE_URL: http://localhost:3001
      NEXT_PUBLIC_CONTENT_SERVICE_URL: http://localhost:3002
      NEXT_PUBLIC_MEDIA_SERVICE_URL: http://localhost:3003
      NEXT_PUBLIC_CATEGORY_SERVICE_URL: http://localhost:3004
      NEXT_PUBLIC_COMMENT_SERVICE_URL: http://localhost:3005
    depends_on:
      - user-service
    networks:
      - cms-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
